[package]
name = "sanakirja-facade"
version = "0.1.0"
authors = ["Joe Neeman <joeneeman@gmail.com>"]

[dependencies]
byteorder = "1.0"
either = "1.1"
rand = "0.3"
sanakirja = { path = "sanakirja" }

[dev-dependencies]
env_logger = "0.4.3"
